name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up the latest Node.js version
      uses: actions/setup-node@v4
      with:
        node-version: '22.x' # Uses the latest available version
        cache: 'npm' # Optional: Caches dependencies for faster installs
             
    - name: Install dependencies
      run: npm ci
        
    - run: npm install -g react-native-cli
    - run: npm install @supabase/supabase-js
    - run: npm install react-native-web react-dom
    - run: npm run web
    - run: npm test

